import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import QueryProvider from "../Providers/QueryProvider/query.js";
import Auth from "../Providers/AuthProvider/Auth.js";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="ar"
      dir="rtl"
      className={`${geistSans.variable} ${geistMono.variable}`}
    >
      <body>
        <QueryProvider>
          <Auth>{children}</Auth>
        </QueryProvider>
        <Toaster />
      </body>
    </html>
  );
}
